name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.tests }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      test_suite:  ${{ matrix.tests }}

    strategy:
      fail-fast: false

      matrix:
        version: ['1.6', '1.7']
        tests: ["basics", "layers", "networks"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout InvertibleNetworks.jl
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Add SLIM registery for JOLI
        run: |
           julia --color=yes --check-bounds=yes -e 'using Pkg;Pkg.update();Pkg.Registry.add(RegistrySpec(url="https://github.com/slimgroup/SLIMregistryJL.git"))'

      - name: Build InvertibleNetworks.jl
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        id: test
        continue-on-error: true  
        uses: julia-actions/julia-runtest@latest

      - name: Retry tests once if failed
        if: steps.test.outcome=='failure' 
        uses: julia-actions/julia-runtest@latest

      - name: Run simple example
        run: julia --project examples/layers/layer_actnorm.jl

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
